// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC1Cxnj-6imNNzXlPG1xyyF6LljK26t78',
    appId: '1:558343328599:web:f7bc9771e4a8744f202412',
    messagingSenderId: '558343328599',
    projectId: 'vt106-aed8c',
    authDomain: 'vt106-aed8c.firebaseapp.com',
    storageBucket: 'vt106-aed8c.appspot.com',
    measurementId: 'G-1896QTZSE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpwpV4y0GGdcd7oLaMAOnbIWqNwyHmefg',
    appId: '1:558343328599:android:4494f453a7d54ca0202412',
    messagingSenderId: '558343328599',
    projectId: 'vt106-aed8c',
    storageBucket: 'vt106-aed8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKI6KwHKcIRXWr0jpqFdqD3RXpHVeBnUk',
    appId: '1:558343328599:ios:6f665e721054b0f2202412',
    messagingSenderId: '558343328599',
    projectId: 'vt106-aed8c',
    storageBucket: 'vt106-aed8c.appspot.com',
    iosClientId: '558343328599-cln30hjqabsli25batqbegpeco4fjuku.apps.googleusercontent.com',
    iosBundleId: 'com.example.eva',
  );
}
